-- BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas, Constraints, Indices e sequences do Projeto Pedido - Parte 3

ALTER TABLE PEDIDO
ADD CONSTRAINT CK_NUMERO_PEDIDO CHECK (NUMERO > 0 AND NUMERO < 100000);

ALTER TABLE PF 
ADD CONSTRAINT UK_PF_CNPF UNIQUE (CNPF);

CREATE INDEX IND_CNPF_PF ON PF (CNPF DESC);


ALTER TABLE PJ
ADD CONSTRAINT UK_PJ_CNPJ UNIQUE (CNPJ);

CREATE INDEX IND_CNPJ_PJ ON PJ (CNPJ DESC);


CREATE SEQUENCE SEQ_ITEM_ID
START WITH 1
INCREMENT BY 2
NOCACHE;