-- BD2 - 2o Bim -Atividade de SQL - Exercícios de DD - Acessando e extraindo metadados

-- 1
SELECT TABLE_NAME AS TABELA
FROM USER_TABLES
ORDER BY TABLE_NAME ASC;

-- 2
SELECT 
    TABLE_NAME AS TABELA,
    COLUMN_NAME AS COLUNA,
    DATA_TYPE AS TIPO_DADO,
    DATA_LENGTH AS TAMANHO
FROM USER_TAB_COLUMNS
ORDER BY TABLE_NAME ASC, COLUMN_NAME DESC;

-- 3
SELECT 
    OWNER AS DONO,
    CONSTRAINT_NAME AS CONSTRAINT,
    CONSTRAINT_TYPE AS TIPO,
    SEARCH_CONDITION AS REGRA
FROM USER_CONSTRAINTS
ORDER BY CONSTRAINT_NAME DESC, CONSTRAINT_TYPE;

-- 4 
SELECT 
    UC.OWNER AS DONO,
    UC.CONSTRAINT_NAME AS CONSTRAINT,
    UCC.TABLE_NAME AS TABELA,
    UCC.COLUMN_NAME AS COLUNA,
    UCC.POSITION AS POSICAO
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC 
    ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
ORDER BY UC.CONSTRAINT_NAME ASC, UCC.COLUMN_NAME ASC;