--BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas do Projeto Pedido - Parte 1
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
CREATE TABLE CLIENTE(
CODIGO  NUMBER,
NOME            VARCHAR2(60) NOT NULL,
RUA             VARCHAR2(80) NOT NULL,         
NR              NUMBER(4) NOT NULL,
BAIRRO          VARCHAR2(50) NOT NULL,        
COMPLEMENTO     VARCHAR2(100) NULL,
CIDADE          VARCHAR2(50) NOT NULL,
UF              VARCHAR2(2) NOT NULL,
CEP             VARCHAR2(10) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

SELECT *
FROM USER_TABLES
WHERE TABLE_NAME IN ('CLIENTE','FONE_CLIENTE');

DESC CLIENTE;

DROP TABLE FONE_CLIENTE CASCADE CONSTRAINTS;
CREATE TABLE FONE_CLIENTE(
NUMERO          VARCHAR2(14),
CODIGO_CLI      NUMBER,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO, CODIGO_CLI),
CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);

--CASO QUEIRA IMPLEMENTAR A FK EXTERNAMENTE
--ALTER TABLE FONE_CLIENTE
--CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO);


DROP TABLE PF CASCADE CONSTRAINTS;
CREATE TABLE PF(
CODIGO_CLI          NUMBER,
CNPF                VARCHAR2(14) NOT NULL,
RG                  VARCHAR2(10) NOT NULL,
DATA_NASCIMENTO     DATE NOT NULL,
CONSTRAINT PK_CLIENTE_PF PRIMARY KEY (CODIGO_CLI),
CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);

DROP TABLE PJ CASCADE CONSTRAINTS;
CREATE TABLE PJ(
CODIGO_CLI          NUMBER,
CNPJ                VARCHAR2(19) NOT NULL,
IE                  VARCHAR2(10) NOT NULL,
NOME_FANTASIA       VARCHAR2(60) NOT NULL,
CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY (CODIGO_CLI),
CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);

DROP TABLE PRODUTO CASCADE CONSTRAINTS;
CREATE TABLE PRODUTO(
CODIGO          NUMBER,
DESCRICAO       VARCHAR2(80)    NOT NULL,
UNID_MEDIDA     VARCHAR2(10)    NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);

DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
CREATE TABLE VENDEDOR(
MATRICULA       NUMBER,
NOME            VARCHAR2(60)    NOT NULL,
CNPF            VARCHAR2(14)    NOT NULL,
CONSTRAINT PK_VENDEDOR PRIMARY KEY (MATRICULA)
);

DROP TABLE FONE_VENDEDOR CASCADE CONSTRAINTS;
CREATE TABLE FONE_VENDEDOR(
NUMERO              VARCHAR2(14),
MATRICULA_VEN       NUMBER,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN),
CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA)
);


DROP TABLE PRATELEIRA CASCADE CONSTRAINTS;
CREATE TABLE PRATELEIRA(
CODIGO          NUMBER(3),
DESCRICAO       VARCHAR(50) NOT NULL,
NUMERO_SECOES   NUMBER(2) NOT NULL,
CONSTRAINT PK_PRATELEIRA PRIMARY KEY (CODIGO)
);

