-- BD2 - 2o Bim - Atividade de SQL - Exercícios de DDL - Comentários em tabelas - Parte 5

COMMENT ON TABLE ITEM_PRODUTO IS 'É A TABELA ENTRE PRODUTO E PEDIDO';

COMMENT ON COLUMN ITEM_PRODUTO.CODIGO_PRO IS 'CÓDIGO IDENTIFICADOR DO PRODUTO QUE SERVIRA COMO PK NA TABELA ITEM_PRODUTO)';
COMMENT ON COLUMN ITEM_PRODUTO.NUMERO_PED IS 'CÓDIGO IDENTIFICADOR DO PEDIDO QUE SERVIRA COMO PK NA TABELA ITEM_PEDIDO';
COMMENT ON COLUMN ITEM_PRODUTO.QUANTIDADE IS 'QUANTIDADE DE UM PRODUTO';
COMMENT ON COLUMN ITEM_PRODUTO.PRECO_UNITARIO IS 'PREÇO INDIVIDUAL DE CADA PRODUTO';
COMMENT ON COLUMN ITEM_PRODUTO.VALOR_ITEM IS 'VALOR TOTAL DADO POR QUANTIDADE * PREÇO UNITARIO';
