-- BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas do Projeto Pedido - Parte 2

SELECT *
FROM USER_TABLES;

-- CRIAÇÃO TABELAS

CREATE TABLE PEDIDO(
NUMERO              NUMBER(6),
DATA                DATE NOT NULL,
PRAZO_ENTREGA       DATE NULL,
RUA                 VARCHAR2(80) NULL,
NR                  NUMBER(4) NULL,
BAIRRO              VARCHAR2(50) NULL,
COMPLEMENTO         VARCHAR2(100) NULL,
CIDADE              VARCHAR2(50) NULL,
UF                  VARCHAR2(2) NULL,
CEP                 VARCHAR2(10) NULL,
TOTAL_FATURA        NUMBER(8,2) NULL,
CODIGO_CLI          NUMBER NOT NULL,
MATRICULA_VEN       NUMBER NOT NULL
);

CREATE TABLE ESTOQUE(
DATA_ENTRADA        DATE,
CODIGO_PRO          NUMBER,
CODIGO_PRA          NUMBER(3),
QUANTIDADE          NUMBER(5) NOT NULL,
DATA_VALIDADE       DATE NULL
);

CREATE TABLE CAPACIDADE_ESTOQUE(
CODIGO_PRO          NUMBER,
CODIGO_PRA          NUMBER(3),
QUANTIDADE          NUMBER(5) NOT NULL
);

CREATE TABLE ITEM_PRODUTO(
CODIGO_PRO          NUMBER,
NUMERO_PED          NUMBER(6),
QUANTIDADE          NUMBER(5) NOT NULL,
PRECO_UNITARIO      NUMBER(5,2) NOT NULL,
VALOR_ITEM          NUMBER(7,2) NULL
);

--CRIAÇÃO PK´s

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (DATA_ENTRADA, CODIGO_PRO, CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY (CODIGO_PRO, CODIGO_PRA);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO, NUMERO_PED);

-- CRIAÇÃO FK´S

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PED) REFERENCES PEDIDO (NUMERO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);







