-- BD2 - 2o Bim -Atividade de SQL - Exercícios de DML - Update - Alterando dados na tabela ITEM_PRODUTO do Projeto Pedido

SELECT 
    NUMERO_PED, 
    CODIGO_PRO, 
    QUANTIDADE
FROM ITEM_PRODUTO
WHERE (NUMERO_PED < 20 OR NUMERO_PED > 50)
  AND CODIGO_PRO BETWEEN 203 AND 205;

UPDATE ITEM_PRODUTO IP
SET IP.QUANTIDADE = IP.QUANTIDADE * 2
WHERE (IP.NUMERO_PED < 20 
   OR IP.NUMERO_PED > 50)
  AND IP.CODIGO_PRO BETWEEN 203 AND 205;


SELECT 
    IP.NUMERO_PED,
    P.CODIGO_CLI,
    P.MATRICULA_VEN,
    IP.CODIGO_PRO,
    IP.QUANTIDADE
FROM ITEM_PRODUTO IP
JOIN PEDIDO P ON P.NUMERO = IP.NUMERO_PED
WHERE MOD(P.CODIGO_CLI, 2) = 1
  AND MOD(P.MATRICULA_VEN, 2) = 0;
  
UPDATE ITEM_PRODUTO IP
SET IP.QUANTIDADE = IP.QUANTIDADE + 15
WHERE EXISTS (
    SELECT 1
    FROM PEDIDO P
    WHERE P.NUMERO = IP.NUMERO_PED
      AND MOD(P.CODIGO_CLI, 2) = 1
      AND MOD(P.MATRICULA_VEN, 2) = 0
);

SELECT 
    NUMERO_PED,
    CODIGO_PRO,
    PRECO_UNITARIO
FROM ITEM_PRODUTO
WHERE MOD(NUMERO_PED, 3) = 0;

UPDATE ITEM_PRODUTO IP
SET IP.PRECO_UNITARIO = IP.PRECO_UNITARIO - 0.50
WHERE MOD(IP.NUMERO_PED, 3) = 0;


SELECT 
    NUMERO_PED,
    CODIGO_PRO,
    QUANTIDADE,
    PRECO_UNITARIO,
    VALOR_ITEM,
    (QUANTIDADE * PRECO_UNITARIO) AS VALOR_CORRETO
FROM ITEM_PRODUTO
WHERE VALOR_ITEM != (QUANTIDADE * PRECO_UNITARIO);

UPDATE ITEM_PRODUTO
SET VALOR_ITEM = QUANTIDADE * PRECO_UNITARIO;

SELECT 
    P.NUMERO AS NUMERO_PEDIDO,
    P.TOTAL_FATURA AS TOTAL_ATUAL,
    SUM(I.VALOR_ITEM) AS TOTAL_CALCULADO
FROM PEDIDO P
LEFT JOIN ITEM_PRODUTO I ON P.NUMERO = I.NUMERO_PED
GROUP BY P.NUMERO, P.TOTAL_FATURA
HAVING P.TOTAL_FATURA != SUM(I.VALOR_ITEM);

UPDATE PEDIDO P
SET P.TOTAL_FATURA = (
    SELECT SUM(I.VALOR_ITEM)
    FROM ITEM_PRODUTO I
    WHERE I.NUMERO_PED = P.NUMERO
);


SELECT *
FROM ITEM_PRODUTO;